[book]
authors = ["Hervy Qurrotul Ainur Rozi"]
language = "id"
multilingual = false
src = "src"
title = "Panduan LangitKetujuh OS"
description = "Panduan dan tutorial menggunakan LangitKetujuh GNU/Linux."

[build]
create-missing = false

[output.html]
default-theme = "light"
preferred-dark-theme = "coal"
git-repository-url= "https://gitlab.com/langitketujuh/book/docs"
edit-url-template = "https://gitlab.com/langitketujuh/book/docs/-/edit/master/src/{path}"
git-repository-icon= "fa-gitlab"
mathjax-support = true

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.linkcheck]
optional = true
