[build]
command = "curl -sL https://github.com/rust-lang/mdBook/releases/download/v0.4.10/mdbook-v0.4.10-x86_64-unknown-linux-gnu.tar.gz | tar xz && ./mdbook build"

[[headers]]
  for = "*.js" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.webp" # css files too
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.css" # css files too
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[redirects]]
  from = "https://panduan-langitketujuh.netlify.app/*"
  to = "https://panduan.langitketujuh.id/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://panduan-langitketujuh.netlify.app/*"
  to = "https://panduan.langitketujuh.id/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://panduan.langitketujuh.id/aplikasi/fish-shell/"
  to = "https://panduan.langitketujuh.id/perintah-dasar/manajemen-paket/"
  status = 301
  force = true

[[redirects]]
  from = "https://panduan.langitketujuh.id/perintah-dasar/fish-shell/"
  to = "https://panduan.langitketujuh.id/perintah-dasar/manajemen-paket/"
  status = 301
  force = true

[[redirects]]
  from = "https://panduan.langitketujuh.id/aplikasi/vpsm/"
  to = "https://panduan.langitketujuh.id/perintah-dasar/vpsm/"
  status = 301
  force = true

[[redirects]]
  from = "https://panduan.langitketujuh.id/layanan/sv/"
  to = "https://panduan.langitketujuh.id/perintah-dasar/sv/"
  status = 301
  force = true

[[redirects]]
  from = "https://panduan.langitketujuh.id/cli/*"
  to = "https://panduan.langitketujuh.id/perintah-dasar/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/404/"
  status = 404
