[build]
command = "curl -L https://github.com/rust-lang/mdBook/releases/download/v0.4.7/mdbook-v0.4.7-x86_64-unknown-linux-gnu.tar.gz | tar xvz && \
  curl -L https://github.com/Michael-F-Bryan/mdbook-linkcheck/releases/download/v0.7.4/mdbook-linkcheck.v0.7.4.x86_64-unknown-linux-gnu.zip | unzip -q && \
  && ./mdbook build"

[[headers]]
  for = "*.js" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.webp" # css files too
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.css" # css files too
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[redirects]]
  from = "https://inkscape.langitketujuh.netlify.app/*"
  to = "https://inkscape.langitketujuh.id/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://inkscape.langitketujuh.netlify.app/*"
  to = "https://inkscape.langitketujuh.id/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/404/"
  status = 404
